#include <qsignalspy.h>
#include <qtest.h>
#include <QtTest/qttestglobal.h>
#include <qtest_gui.h>
//#include <qtestaccessible.h>
#include <qtestassert.h>
#include <qtestcase.h>
#include <qtestdata.h>
#include <qtestevent.h>
#include <qtesteventloop.h>
#include <qtestkeyboard.h>
#include <qtestmouse.h>
#include <qtestspontaneevent.h>
#include <qtestsystem.h>
