<config>
    <resolveTypedefs>true</resolveTypedefs>
    <qtMode>true</qtMode>
    <generator>smoke</generator>
    <definesList>@CMAKE_INSTALL_PREFIX@/share/smokegen/qtdefines</definesList>
    <includeDirs>
        @QT_ALL_INCLUDE_DIRS_XML@
    </includeDirs>
</config>
