<config>
    <resolveTypedefs>true</resolveTypedefs>
    <qtMode>true</qtMode>
    <generator>smoke</generator>
    <definesList>@CMAKE_BINARY_DIR@/smoke/qtdefines</definesList>
    <includeDirs>
        @QT_INCLUDE_DIRS_XML@
        <dir>@OPENGL_INCLUDE_DIR@</dir>
    </includeDirs>
</config>
