name: Ubuntu-24.04, Ruby-3.2

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install Package Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ruby-dev qtbase5-dev libqt5opengl5-dev qttools5-dev qtscript5-dev libqt5svg5-dev libqt5webkit5-dev libqt5x11extras5-dev libqt5xmlpatterns5-dev qtmultimedia5-dev qtdeclarative5-dev libclang-dev clang
    - name: Build and test with Rake
      run: rake
